<?php

include_once("//var/www/gip/app/settings/gipConfiguration.inc.php");

// APP COMPONENTS
// COMMON
define("COMMON_COMPONENT",APP_PATH.FILE_SEPARATOR."common"); 

// Common Error Handler
define("ERROR_HANDLING_COMPONENT",COMMON_COMPONENT.FILE_SEPARATOR."errorHandler"); 
define("CLASS_ERROR_HANDLER",ERROR_HANDLING_COMPONENT.FILE_SEPARATOR."errorHandler.class.php"); 

// Common Lib
define("LIB_COMPONENT",COMMON_COMPONENT.FILE_SEPARATOR."lib"); 
define("CLASS_ADODB",LIB_COMPONENT.FILE_SEPARATOR."adodb".FILE_SEPARATOR."adodb.inc.php"); 
define("CLASS_HTML_EMAIL",LIB_COMPONENT.FILE_SEPARATOR."htmlMimeMail-2.5.1".FILE_SEPARATOR."htmlMimeMail.php"); 
define("CODE_BEAUTIFIER_REQ",LIB_COMPONENT.FILE_SEPARATOR."codeBeautifier".FILE_SEPARATOR."Beautifier".FILE_SEPARATOR."Init.php"); 


// Common Database
define("DATABASE_COMPONENT",COMMON_COMPONENT.FILE_SEPARATOR."database"); 
define("CLASS_DATABASE_CONNECTION_POOL",DATABASE_COMPONENT.FILE_SEPARATOR."databaseConnectionPool.class.php"); 
define("CLASS_DATABASE_QUERY",DATABASE_COMPONENT.FILE_SEPARATOR."databaseQuery.class.php"); 
define("CLASS_DATABASE_UTILS",DATABASE_COMPONENT.FILE_SEPARATOR."databaseUtils.class.php"); 


// Common UTILITIES 
define("UTILS_COMPONENT",COMMON_COMPONENT.FILE_SEPARATOR."utils"); 
define("CLASS_PAGE_TIMER",UTILS_COMPONENT.FILE_SEPARATOR."pageTimer".FILE_SEPARATOR."pageTimer.class.php"); 

define("CLASS_REQUEST_UTILS",UTILS_COMPONENT.FILE_SEPARATOR."requestUtils".FILE_SEPARATOR."requestUtils.class.php");
define("CLASS_TEXT_ENCRYPTER",UTILS_COMPONENT.FILE_SEPARATOR."textEncrypter".FILE_SEPARATOR."textEncrypter.class.php"); 
define("CLASS_PHP_CODE_BEAUTIFIER",UTILS_COMPONENT.FILE_SEPARATOR."phpCodeBeautifier".FILE_SEPARATOR."phpCodeBeautifier.class.php"); 
define("CLASS_PHP_BEAUTIFY",UTILS_COMPONENT.FILE_SEPARATOR."phpCodeBeautifier".FILE_SEPARATOR."beautify_php.class.php"); 
define("CLASS_PEAR",UTILS_COMPONENT.FILE_SEPARATOR."phpCodeBeautifier".FILE_SEPARATOR."PEAR.class.php"); 

// HTML FORM ELEMENT BUILDER UTILS
define("CLASS_HTML_FORM_ELEMENT_BUILDER",UTILS_COMPONENT.FILE_SEPARATOR."htmlElementBuilder".FILE_SEPARATOR."htmlFormElementBuilder.class.php"); 

// FILE SYSTEM
define("CLASS_FILESYSTEM_UTILS",UTILS_COMPONENT.FILE_SEPARATOR."fileSystem".FILE_SEPARATOR."fileSystemUtils.class.php");

// STRING REPLACER
define("CLASS_STRING_UTILS",UTILS_COMPONENT.FILE_SEPARATOR."stringUtils".FILE_SEPARATOR."stringUtils.class.php");
define("CLASS_PAIR",UTILS_COMPONENT.FILE_SEPARATOR."stringUtils".FILE_SEPARATOR."pair.class.php");

// GENERATORS COMPONENT
define("CLASS_GENERATOR_COMPONENT",APP_PATH.FILE_SEPARATOR."generators");


// DB ENGINE
define("CLASS_DB_ENGINE_COMPONENT",CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."dbEngine");
define("CLASS_DATABASE",CLASS_DB_ENGINE_COMPONENT.FILE_SEPARATOR."database.class.php");
define("CLASS_TABLE",CLASS_DB_ENGINE_COMPONENT.FILE_SEPARATOR."table.class.php");
define("CLASS_FIELDINFO",CLASS_DB_ENGINE_COMPONENT.FILE_SEPARATOR."fieldInfo.class.php");

// SEARCH UTILS 
define("SEARCH_UTIL_COMPONENT",COMMON_COMPONENT.FILE_SEPARATOR."search"); 
define("CLASS_SEARCH_ITEM",SEARCH_UTIL_COMPONENT.FILE_SEPARATOR."searchItem.class.php"); 
define("CLASS_SEARCH_UTILS",SEARCH_UTIL_COMPONENT.FILE_SEPARATOR."searchUtils.class.php"); 


// SQL ENGINE
define("CLASS_SQL_ENGINE_COMPONENT",CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."sqlEngine");
define("CLASS_SQL_BUILDER",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."sqlBuilder.class.php");
define("CLASS_SQL_ENGINE",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."sqlEngine.class.php");

define("CLASS_SQL_ENGINE_INSERT_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."insertSQLGenerator.class.php");
define("CLASS_SQL_ENGINE_DELETE_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."deleteSQLGenerator.class.php");
define("CLASS_SQL_ENGINE_SELECT_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."selectSQLGenerator.class.php");
define("CLASS_SQL_ENGINE_UPDATE_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."updateSQLGenerator.class.php");
define("CLASS_SQL_ENGINE_SELECT_KEYWORD_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."selectKeywordGenerator.class.php");
define("CLASS_SQL_ENGINE_CREATE_GENERATOR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."createSQLGenerator.class.php");


define("CLASS_NAME_VALUE_PAIR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."nameValuePair.class.php");
define("CLASS_WHERE_PAIR",CLASS_SQL_ENGINE_COMPONENT.FILE_SEPARATOR."wherePair.class.php"); 

// GENERATOR UTILS
define("CLASS_GENERATOR_UTILS_COMPONENT",CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."utils");
define("CLASS_COMMON_OBJECT_COPIER",CLASS_GENERATOR_UTILS_COMPONENT.FILE_SEPARATOR."commonObjectsCopier.class.php");


// PLUGIN MANAGER COMPONENT
define("CLASS_PLUGIN_MANAGER_COMPONENT",CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."plugInManager");
define("CLASS_PLUGIN_LOADER",CLASS_PLUGIN_MANAGER_COMPONENT.FILE_SEPARATOR."pluginLoader.class.php");



// PHP GENERATOR COMPONENT
define("CLASS_PHP_CODE_GENERATOR_COMPONENT",CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."php");
define("CLASS_PHP_PLUGINS_COMPONENT",CLASS_PHP_CODE_GENERATOR_COMPONENT.FILE_SEPARATOR."plugins");
define("CLASS_PHP_PLUGIN_GIP_FRAMEWORK_COMPONENT",CLASS_PHP_PLUGINS_COMPONENT.FILE_SEPARATOR."gipDbFrameworkGenerator");

// Common Framework 
define("CLASS_COMMON_GIP_FRAMEWORK",CLASS_PHP_PLUGIN_GIP_FRAMEWORK_COMPONENT.FILE_SEPARATOR."commonGenieFramework.class.php");


// PHP CLASS GENERATOR
define("CLASS_PHP_CLASS_GENERATOR_COMPONENT",CLASS_PHP_CODE_GENERATOR_COMPONENT.FILE_SEPARATOR."phpClassGenerator");
define("CLASS_PHP_CLASS_GENERATOR",CLASS_PHP_CLASS_GENERATOR_COMPONENT.FILE_SEPARATOR."phpClassGenerator.class.php");

// PHP SIMPLE DB GENERATOR
define("CLASS_PHP_SIMPLE_DB_GENERATOR_COMPONENT",CLASS_PHP_PLUGINS_COMPONENT.FILE_SEPARATOR."simpleDbGenerator");
define("CLASS_COMMON_SIMPLE_DB_GENERATOR",CLASS_PHP_SIMPLE_DB_GENERATOR_COMPONENT.FILE_SEPARATOR."commonSimpleDbGenerator.class.php");


// PHP GIP DB FRAMEWORK GENERATOR
define("CLASS_PHP_GIP_DB_FRAMEWORK_GENERATOR_COMPONENT",CLASS_PHP_PLUGINS_COMPONENT.FILE_SEPARATOR."gipDbFrameworkGenerator");

// GIP WEB DB FRAMEWORK GENERATOR
define("CLASS_PHP_GIP_DB_WEB_FRAMEWORK_GENERATOR_COMPONENT",CLASS_PHP_GIP_DB_FRAMEWORK_GENERATOR_COMPONENT.FILE_SEPARATOR."webComponentGenerator");


// GIP APP DB FRAMEWORK GENERATOR
define("CLASS_PHP_GIP_DB_APP_FRAMEWORK_GENERATOR_COMPONENT",CLASS_PHP_GIP_DB_FRAMEWORK_GENERATOR_COMPONENT.FILE_SEPARATOR."appComponentGenerator");


// GIP COMMON DB FRAMEWORK GENERATOR
define("CLASS_PHP_GIP_DB_COMMON_FRAMEWORK_GENERATOR_COMPONENT",CLASS_PHP_GIP_DB_FRAMEWORK_GENERATOR_COMPONENT.FILE_SEPARATOR."commonComponentGenerator");


// GIP FRAMEWORK UTILS
define("CLASS_PHP_GIP_UTILS_COMPONENT",CLASS_PHP_GIP_DB_FRAMEWORK_GENERATOR_COMPONENT.FILE_SEPARATOR."utils");
define("CLASS_PHP_GIP_UTILS_COMMON_FILE_COPIER",CLASS_PHP_GIP_UTILS_COMPONENT.FILE_SEPARATOR."gipCommonFileCopier.class.php");
define("CLASS_PHP_GIP_UTILS_INDEX_BUILDER",CLASS_PHP_GIP_UTILS_COMPONENT.FILE_SEPARATOR."gipIndexBuilder.class.php");

?>
