<?php

define("PLUGIN_PHP_GENERATOR_COMPONENT",PLUGIN_GENERATORS_COMPONENT.FILE_SEPARATOR."php");
define("PLUGIN_PHP_PLUGIN_COMPONENT",PLUGIN_PHP_GENERATOR_COMPONENT.FILE_SEPARATOR."plugins");

// GenieFrameWork Plugin
define("PLUGIN_PHP_GIP_FRAMEWORK_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."gipDbFrameworkGenerator");

define("PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT",PLUGIN_PHP_GIP_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."appComponentGenerator");
define("PLUGIN_PHP_GIP_FRAMEWORK_COMMON_COMPONENT",PLUGIN_PHP_GIP_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."commonComponentGenerator");
define("PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT",PLUGIN_PHP_GIP_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."webComponentGenerator");

// GIP APP COMPONENT GENERATOR
define("PLUGIN_PHP_GIP_APP_DAO_INSERT_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_INSERT_GENERATOR_NAME","gipDAOInsertGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_UPDATE_GENERATOR_NAME","gipDAOUpdateGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_DELETE_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAODeleteGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_DELETE_GENERATOR_NAME","gipDAODeleteGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_DELETEBYID_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAODeleteByIdGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_DELETEBYID_GENERATOR_NAME","gipDAODeleteByIdGenerator");


define("PLUGIN_PHP_GIP_APP_DAO_GETBYID_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOGetByIdGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_GETBYID_GENERATOR_NAME","gipDAOGetByIdGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_GETALL_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOGetAllGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_GETALL_GENERATOR_NAME","gipDAOGetAllGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_SEARCH_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOSearchGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_SEARCH_GENERATOR_NAME","gipDAOSearchGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_SEARCHBYKEYWORD_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOSearchByKeywordGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_SEARCHBYKEYWORD_GENERATOR_NAME","gipDAOSearchByKeywordGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_POPULATEINTOINFO_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOPopulateIntoInfoGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_POPULATEINTOINFO_GENERATOR_NAME","gipDAOPopulateIntoInfoGenerator");

define("PLUGIN_PHP_GIP_APP_GENMANAGER_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipGenManagerGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_GENMANAGER_GENERATOR_NAME","gipGenManagerGenerator");

define("PLUGIN_PHP_GIP_APP_MANAGER_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipManagerGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_MANAGER_GENERATOR_NAME","gipManagerGenerator");


define("PLUGIN_PHP_GIP_APP_GENDAO_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipGenDaoGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_GENDAO_GENERATOR_NAME","gipGenDaoGenerator");

define("PLUGIN_PHP_GIP_APP_DAO_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipDAOGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_DAO_GENERATOR_NAME","gipDAOGenerator");


define("PLUGIN_PHP_GIP_APP_INFO_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."gipInfoGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_APP_INFO_GENERATOR_NAME","gipInfoGenerator");


// GIP WEB COMPONENT GENERATOR

define("PLUGIN_PHP_GIP_WEB_ENTER_FORM_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebEnterFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_ENTER_FORM_GENERATOR_NAME","gipWebEnterFormGenerator");

define("PLUGIN_PHP_GIP_WEB_INSERT_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_INSERT_GENERATOR_NAME","gipWebInsertGenerator");

define("PLUGIN_PHP_GIP_WEB_EDIT_FORM_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebEditFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_EDIT_FORM_GENERATOR_NAME","gipWebEditFormGenerator");

define("PLUGIN_PHP_GIP_WEB_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_UPDATE_GENERATOR_NAME","gipWebUpdateGenerator");

define("PLUGIN_PHP_GIP_WEB_DELETE_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebDeleteScriptGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_DELETE_GENERATOR_NAME","gipWebDeleteScriptGenerator");

define("PLUGIN_PHP_GIP_WEB_DELETE_CONFIRMATION_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebDeleteConfirmationGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_DELETE_CONFIRMATION_GENERATOR_NAME","gipWebDeleteConfirmationGenerator");

define("PLUGIN_PHP_GIP_WEB_POWER_SEARCH_FORM_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebPowerSearchFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_POWER_SEARCH_FORM_GENERATOR_NAME","gipWebPowerSearchFormGenerator");

define("PLUGIN_PHP_GIP_WEB_POWER_SEARCH_SCRIPT_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebPowerSearchScriptGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_POWER_SEARCH_SCRIPT_GENERATOR_NAME","gipWebPowerSearchScriptGenerator");



define("PLUGIN_PHP_GIP_WEB_VIEW_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebViewGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_VIEW_GENERATOR_NAME","gipWebViewGenerator");

define("PLUGIN_PHP_GIP_WEB_LISTALL_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebListAllGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_LISTALL_GENERATOR_NAME","gipWebListAllGenerator");


define("PLUGIN_PHP_GIP_WEB_CRUD_GRID_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebCrudGridGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_CRUD_GRID_GENERATOR_NAME","gipWebCrudGridGenerator");


define("PLUGIN_PHP_GIP_WEB_INDEX_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."gipWebMainIndexGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_WEB_INDEX_GENERATOR_NAME","gipWebMainIndexGenerator");



// SIMPLE PHP PLUGINS
define("PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDbGenerator");
define("PLUGIN_PHP_SIMPLE_WEB_INSERT_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_INSERT_GENERATOR_NAME","simpleInsertGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_UPDATE_GENERATOR_NAME","simpleUpdateGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_DELETE_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDeleteGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_DELETE_GENERATOR_NAME","simpleDeleteGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_DELETE_CONFIRMATION_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDeleteConfirmationGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_DELETE_CONFIRMATION_GENERATOR_NAME","simpleDeleteConfirmationGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_VIEW_RECORD_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleViewRecordGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_VIEW_RECORD_GENERATOR_NAME","simpleViewRecordGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GRID_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleListerGridGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GRID_GENERATOR_NAME","simpleListerGridGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleListerGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GENERATOR_NAME","simpleListerGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_ENTER_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleEnterFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_ENTER_FORM_GENERATOR_NAME","simpleEnterFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_EDIT_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleEditFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_EDIT_FORM_GENERATOR_NAME","simpleEditFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simplePowerSearchFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_FORM_GENERATOR_NAME","simplePowerSearchFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simplePowerSearchGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_NAME","simplePowerSearchGenerator");

define("PLUGIN_PHP_SIMPLE_MAIN_INDEX_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleMainIndexGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_MAIN_INDEX_GENERATOR_NAME","simpleMainIndexGenerator");


// COMMON PHP PLUGINS
define("PLUGIN_PHP_GIP_COMMONDB_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."gipCommonDbConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_COMMONDB_GENERATOR_NAME","gipCommonDbConstantsGenerator");

define("PLUGIN_PHP_GIP_CONFIGURATION_FILE_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."gipConfigurationFileGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_CONFIGURATION_FILE_GENERATOR_NAME","gipConfigurationFileGenerator");


define("PLUGIN_PHP_GIP_COMMONPAGES_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."gipCommonPageConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_COMMONPAGES_GENERATOR_NAME","gipCommonPageConstantsGenerator");

define("PLUGIN_PHP_GIP_COMMON_CLASSES_GENERATOR_CLASS",PLUGIN_PHP_GIP_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."gipCommonClassConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GIP_COMMON_CLASSES_GENERATOR_NAME","gipCommonClassConstantsGenerator");

// PHP CLASS GENERATOR
define("PLUGIN_PHP_CLASS_GENERATOR_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."phpClassGenerator");
define("PLUGIN_PHP_CLASS_GENERATOR_CLASS",PLUGIN_PHP_CLASS_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."phpClassGenerator.plugin.class.php");
define("PLUGIN_PHP_CLASS_GENERATOR_NAME","phpClassGenerator");



?>