<?php

define("PLUGIN_PHP_GENERATOR_COMPONENT",PLUGIN_GENERATORS_COMPONENT.FILE_SEPARATOR."php");
define("PLUGIN_PHP_PLUGIN_COMPONENT",PLUGIN_PHP_GENERATOR_COMPONENT.FILE_SEPARATOR."plugins");

// GenieFrameWork Plugin
define("PLUGIN_PHP_GENIE_FRAMEWORK_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."genieDbFrameworkGenerator");

define("PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT",PLUGIN_PHP_GENIE_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."appComponentGenerator");
define("PLUGIN_PHP_GENIE_FRAMEWORK_COMMON_COMPONENT",PLUGIN_PHP_GENIE_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."commonComponentGenerator");
define("PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT",PLUGIN_PHP_GENIE_FRAMEWORK_PLUGIN_COMPONENT.FILE_SEPARATOR."webComponentGenerator");

// GENIE APP COMPONENT GENERATOR
define("PLUGIN_PHP_GENIE_APP_DAO_INSERT_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_INSERT_GENERATOR_NAME","genieDAOInsertGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_UPDATE_GENERATOR_NAME","genieDAOUpdateGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_DELETE_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAODeleteGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_DELETE_GENERATOR_NAME","genieDAODeleteGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_DELETEBYID_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAODeleteByIdGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_DELETEBYID_GENERATOR_NAME","genieDAODeleteByIdGenerator");


define("PLUGIN_PHP_GENIE_APP_DAO_GETBYID_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOGetByIdGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_GETBYID_GENERATOR_NAME","genieDAOGetByIdGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_GETALL_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOGetAllGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_GETALL_GENERATOR_NAME","genieDAOGetAllGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_SEARCH_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOSearchGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_SEARCH_GENERATOR_NAME","genieDAOSearchGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_SEARCHBYKEYWORD_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOSearchByKeywordGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_SEARCHBYKEYWORD_GENERATOR_NAME","genieDAOSearchByKeywordGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_POPULATEINTOINFO_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOPopulateIntoInfoGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_POPULATEINTOINFO_GENERATOR_NAME","genieDAOPopulateIntoInfoGenerator");

define("PLUGIN_PHP_GENIE_APP_GENMANAGER_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieGenManagerGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_GENMANAGER_GENERATOR_NAME","genieGenManagerGenerator");

define("PLUGIN_PHP_GENIE_APP_MANAGER_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieManagerGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_MANAGER_GENERATOR_NAME","genieManagerGenerator");


define("PLUGIN_PHP_GENIE_APP_GENDAO_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieGenDaoGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_GENDAO_GENERATOR_NAME","genieGenDaoGenerator");

define("PLUGIN_PHP_GENIE_APP_DAO_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieDAOGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_DAO_GENERATOR_NAME","genieDAOGenerator");


define("PLUGIN_PHP_GENIE_APP_INFO_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_APP_COMPONENT.FILE_SEPARATOR."genieInfoGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_APP_INFO_GENERATOR_NAME","genieInfoGenerator");


// GENIE WEB COMPONENT GENERATOR

define("PLUGIN_PHP_GENIE_WEB_ENTER_FORM_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebEnterFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_ENTER_FORM_GENERATOR_NAME","genieWebEnterFormGenerator");

define("PLUGIN_PHP_GENIE_WEB_INSERT_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_INSERT_GENERATOR_NAME","genieWebInsertGenerator");

define("PLUGIN_PHP_GENIE_WEB_EDIT_FORM_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebEditFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_EDIT_FORM_GENERATOR_NAME","genieWebEditFormGenerator");

define("PLUGIN_PHP_GENIE_WEB_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_UPDATE_GENERATOR_NAME","genieWebUpdateGenerator");

define("PLUGIN_PHP_GENIE_WEB_DELETE_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebDeleteScriptGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_DELETE_GENERATOR_NAME","genieWebDeleteScriptGenerator");

define("PLUGIN_PHP_GENIE_WEB_DELETE_CONFIRMATION_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebDeleteConfirmationGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_DELETE_CONFIRMATION_GENERATOR_NAME","genieWebDeleteConfirmationGenerator");

define("PLUGIN_PHP_GENIE_WEB_POWER_SEARCH_FORM_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebPowerSearchFormGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_POWER_SEARCH_FORM_GENERATOR_NAME","genieWebPowerSearchFormGenerator");

define("PLUGIN_PHP_GENIE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebPowerSearchScriptGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_NAME","genieWebPowerSearchScriptGenerator");



define("PLUGIN_PHP_GENIE_WEB_VIEW_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebViewGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_VIEW_GENERATOR_NAME","genieWebViewGenerator");

define("PLUGIN_PHP_GENIE_WEB_LISTALL_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebListAllGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_LISTALL_GENERATOR_NAME","genieWebListAllGenerator");


define("PLUGIN_PHP_GENIE_WEB_CRUD_GRID_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebCrudGridGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_CRUD_GRID_GENERATOR_NAME","genieWebCrudGridGenerator");


define("PLUGIN_PHP_GENIE_WEB_INDEX_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_WEB_COMPONENT.FILE_SEPARATOR."genieWebMainIndexGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_WEB_INDEX_GENERATOR_NAME","genieWebMainIndexGenerator");



// SIMPLE PHP PLUGINS
define("PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDbGenerator");
define("PLUGIN_PHP_SIMPLE_WEB_INSERT_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleInsertGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_INSERT_GENERATOR_NAME","simpleInsertGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_UPDATE_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleUpdateGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_UPDATE_GENERATOR_NAME","simpleUpdateGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_DELETE_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDeleteGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_DELETE_GENERATOR_NAME","simpleDeleteGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_DELETE_CONFIRMATION_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleDeleteConfirmationGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_DELETE_CONFIRMATION_GENERATOR_NAME","simpleDeleteConfirmationGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_VIEW_RECORD_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleViewRecordGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_VIEW_RECORD_GENERATOR_NAME","simpleViewRecordGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GRID_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleListerGridGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GRID_GENERATOR_NAME","simpleListerGridGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleListerGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_LISTER_GENERATOR_NAME","simpleListerGenerator");


define("PLUGIN_PHP_SIMPLE_WEB_ENTER_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleEnterFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_ENTER_FORM_GENERATOR_NAME","simpleEnterFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_EDIT_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleEditFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_EDIT_FORM_GENERATOR_NAME","simpleEditFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_FORM_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simplePowerSearchFormGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_FORM_GENERATOR_NAME","simplePowerSearchFormGenerator");

define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simplePowerSearchGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_WEB_POWER_SEARCH_SCRIPT_GENERATOR_NAME","simplePowerSearchGenerator");

define("PLUGIN_PHP_SIMPLE_MAIN_INDEX_GENERATOR_CLASS",PLUGIN_PHP_SIMPLE_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."simpleMainIndexGenerator.plugin.class.php");
define("PLUGIN_PHP_SIMPLE_MAIN_INDEX_GENERATOR_NAME","simpleMainIndexGenerator");


// COMMON PHP PLUGINS
define("PLUGIN_PHP_GENIE_COMMONDB_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."genieCommonDbConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_COMMONDB_GENERATOR_NAME","genieCommonDbConstantsGenerator");

define("PLUGIN_PHP_GENIE_CONFIGURATION_FILE_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."genieConfigurationFileGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_CONFIGURATION_FILE_GENERATOR_NAME","genieConfigurationFileGenerator");


define("PLUGIN_PHP_GENIE_COMMONPAGES_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."genieCommonPageConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_COMMONPAGES_GENERATOR_NAME","genieCommonPageConstantsGenerator");

define("PLUGIN_PHP_GENIE_COMMON_CLASSES_GENERATOR_CLASS",PLUGIN_PHP_GENIE_FRAMEWORK_COMMON_COMPONENT.FILE_SEPARATOR."genieCommonClassConstantsGenerator.plugin.class.php");
define("PLUGIN_PHP_GENIE_COMMON_CLASSES_GENERATOR_NAME","genieCommonClassConstantsGenerator");

// PHP CLASS GENERATOR
define("PLUGIN_PHP_CLASS_GENERATOR_PLUGIN_COMPONENT",PLUGIN_PHP_PLUGIN_COMPONENT.FILE_SEPARATOR."phpClassGenerator");
define("PLUGIN_PHP_CLASS_GENERATOR_CLASS",PLUGIN_PHP_CLASS_GENERATOR_PLUGIN_COMPONENT.FILE_SEPARATOR."phpClassGenerator.plugin.class.php");
define("PLUGIN_PHP_CLASS_GENERATOR_NAME","phpClassGenerator");



?>