<?php

include_once("//var/www/gip/app/settings/gipConfiguration.inc.php");

// APP COMPONENTS
// COMMON
define("TOOLS_WEB_COMPONENT",URL_ADDRESS.WEB_SEPARATOR."tools"); 

define("PHP_STYLE_SHEET_VIEWER_COMPONENT",TOOLS_WEB_COMPONENT.FILE_SEPARATOR."phpStyleSheetViewer"); 
define("TOOL_PHP_STYLE_SHEET_VIEWER",PHP_STYLE_SHEET_VIEWER_COMPONENT.FILE_SEPARATOR."phpStyleSheetViewer.php"); 

define("TOOLS_GEN_CONVERT_TOOL_COMPONENT",TOOLS_WEB_COMPONENT.FILE_SEPARATOR."generatorConvertTool"); 
define("TOOLS_GEN_CONVERT_TOOL_ENTER_CODE",TOOLS_GEN_CONVERT_TOOL_COMPONENT.FILE_SEPARATOR."enterCodeToConvert.php"); 
define("TOOLS_GEN_CONVERT_TOOL_CONVERT",TOOLS_GEN_CONVERT_TOOL_COMPONENT.FILE_SEPARATOR."convertCode.php"); 

define("TOOLS_GEN_EXTRACT_FROM_FORM_TOOL_COMPONENT",TOOLS_WEB_COMPONENT.FILE_SEPARATOR."formExtractor"); 
define("TOOLS_GEN_EXTRACT_FROM_FORM_ENTER_CODE",TOOLS_GEN_EXTRACT_FROM_FORM_TOOL_COMPONENT.FILE_SEPARATOR."enterCodeToExtractFrom.php"); 
define("TOOLS_GEN_EXTRACT_FROM_FORM_EXTRACT",TOOLS_GEN_EXTRACT_FROM_FORM_TOOL_COMPONENT.FILE_SEPARATOR."extractFormElements.php"); 


define("TOOLS_LANGUAGE_FILE_BUILDER_COMPONENT",TOOLS_WEB_COMPONENT.FILE_SEPARATOR."languageFileBuilder"); 
define("TOOLS_LANGUAGE_BUILD_NEW_LANGUAGE_FILE",TOOLS_LANGUAGE_FILE_BUILDER_COMPONENT.FILE_SEPARATOR."buildNewLanguageFile.php"); 
define("TOOLS_LANGUAGE_PROCESS_LANGUAGE_FILE",TOOLS_LANGUAGE_FILE_BUILDER_COMPONENT.FILE_SEPARATOR."processLanguageFile.php"); 
define("TOOLS_LANGUAGE_SAVE_LANGUAGE_FILE_FOR_USER",TOOLS_LANGUAGE_FILE_BUILDER_COMPONENT.FILE_SEPARATOR."saveLanguageFileForUser.php"); 



define("TOOLS_GEN_JAVA_EJB",PAGE_GENERATOR_JAVA_COMPONENT.FILE_SEPARATOR."ejb".FILE_SEPARATOR."chooseFieldTypesForEjbGen.php"); 

define("TOOLS_GEN_SQL",PAGE_GENERATOR_SQL_COMPONENT.FILE_SEPARATOR."generateAllSql.php"); 

// Nonsense Generator
define("TOOLS_GEN_NONSENSE_GENERATOR_COMPONENT",TOOLS_WEB_COMPONENT.FILE_SEPARATOR."nonsenseGenerator"); 
define("TOOLS_GEN_GENERATE_NONSENSE",TOOLS_GEN_NONSENSE_GENERATOR_COMPONENT.FILE_SEPARATOR."generateNonsense.php"); 



?>
